services:
  cassandra_01:
    image: cassandra:5.0.8
    container_name: cassandra_01
    ports:
      - 9042:9042
    volumes:
      - cassandra-node-01:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: nanourl
      CASSANDRA_SEEDS: cassandra_01
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra_02:
    image: cassandra:5.0.8
    container_name: cassandra_02
    depends_on:
      cassandra_01:
        condition: service_healthy
    volumes:
      - cassandra-node-02:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: nanourl
      CASSANDRA_SEEDS: cassandra_01
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra_03:
    image: cassandra:5.0.8
    container_name: cassandra_03
    depends_on:
      cassandra_02:
        condition: service_healthy
    volumes:
      - cassandra-node-03:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: nanourl
      CASSANDRA_SEEDS: cassandra_01
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra_init:
    image: cassandra:5.0.8
    container_name: cassandra_init
    depends_on:
      cassandra_01:
        condition: service_healthy
    volumes:
      - ./cassandra/init.prod.cql:/init.cql:ro
    entrypoint:
      - sh
      - -c
      - cqlsh cassandra_01 -f /init.cql
    restart: "no"

  server_01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_01
    depends_on:
      cassandra_init:
        condition: service_completed_successfully
    environment:
      MACHINE_ID: 1

  server_02:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_02
    depends_on:
      cassandra_init:
        condition: service_completed_successfully
    environment:
      MACHINE_ID: 2

  server_03:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_03
    depends_on:
      cassandra_init:
        condition: service_completed_successfully
    environment:
      MACHINE_ID: 3


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - server_01
      - server_02
      - server_03

  redis:
    image: redis:8.10.0
    container_name: redis
    ports:
      - 6379:6379

volumes:
  cassandra-node-01:
  cassandra-node-02:
  cassandra-node-03: