events {}

http {
    upstream nanourl {
        server server_01:8080;
        server server_02:8080;
        server server_03:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nanourl;
        }
    }
}